from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any, Protocol

from .opportunity import Opportunity, average_order_value, impact_from_revenue


class SupportsDetection(Protocol):
    def site_summary(self, start_date: str, end_date: str) -> list[dict[str, Any]]: ...
    def funnel(self, start_date: str, end_date: str) -> list[dict[str, Any]]: ...
    def search_performance(self, start_date: str, end_date: str) -> list[dict[str, Any]]: ...
    def inventory_friction(self, start_date: str, end_date: str) -> list[dict[str, Any]]: ...
    def available_event_dates(self) -> list[str]: ...
    def daily_performance(self, start_date: str, end_date: str) -> list[dict[str, Any]]: ...


BASELINE_READY_PRIOR_DAYS = 6
REVENUE_ANOMALY_THRESHOLD = 0.20
FUNNEL_ANOMALY_THRESHOLD = 0.15
INVENTORY_RECOVERY_RATE = 0.20
INVENTORY_BACKORDER_RECOVERY_RATE = 0.05
SEARCH_RECOVERY_RATE = 0.10
FUNNEL_RECOVERY_OF_NON_CART = 0.02
FUNNEL_REVENUE_SHARE_CAP = 0.15


def detect_opportunities(
    tools: SupportsDetection,
    date: str,
    *,
    limit: int = 3,
    lookback_days: int = 7,
) -> dict[str, Any]:
    """Detect and rank read-only revenue opportunities without calling an LLM."""
    _validate_date(date)
    if limit < 1:
        raise ValueError("limit must be >= 1")

    summary_rows = tools.site_summary(date, date)
    funnel_rows = tools.funnel(date, date)
    inventory = tools.inventory_friction(date, date)
    searches = tools.search_performance(date, date)

    summary = summary_rows[0] if summary_rows else {}
    funnel = funnel_rows[0] if funnel_rows else {}
    aov = average_order_value(summary)

    available = _available_dates(tools)
    prior_dates = [d for d in available if d < date][-lookback_days:]
    baseline_ready = len(prior_dates) >= BASELINE_READY_PRIOR_DAYS
    series = []
    if prior_dates or date in available:
        start = prior_dates[0] if prior_dates else date
        series = tools.daily_performance(start, date)

    opportunities: list[Opportunity] = []
    opportunities.extend(_inventory_opportunities(date, inventory, aov))
    opportunities.extend(_search_opportunities(date, searches, aov))
    opportunities.extend(_funnel_opportunities(date, funnel, aov, summary))
    opportunities.extend(_baseline_opportunities(date, series, prior_dates, baseline_ready))

    ranked = sorted(
        opportunities,
        key=lambda item: (
            item.estimated_monthly_revenue_usd if item.estimated_monthly_revenue_usd is not None else -1,
            item.confidence,
        ),
        reverse=True,
    )[:limit]

    return {
        "date": date,
        "baseline_days": len(prior_dates),
        "baseline_ready": baseline_ready,
        "site_aov_usd": round(aov, 2) if aov is not None else None,
        "opportunity_count": len(ranked),
        "opportunities": [item.to_dict() for item in ranked],
        "notes": [
            "Opportunities are generated by deterministic detectors; no model was invoked.",
            "Estimated monthly revenue assumes the observed daily pattern persists for 30 days.",
            "Recovery rates are conservative placeholders until experiment results exist.",
            (
                "Baseline anomaly detection activates after "
                f"{BASELINE_READY_PRIOR_DAYS} prior daily exports."
                if not baseline_ready
                else "Baseline anomaly detection is active."
            ),
        ],
    }


def _available_dates(tools: SupportsDetection) -> list[str]:
    try:
        return sorted(tools.available_event_dates())
    except Exception:
        return []


def _inventory_opportunities(
    date: str,
    inventory: list[dict[str, Any]],
    aov: float | None,
) -> list[Opportunity]:
    if not inventory:
        return []
    top = inventory[0]
    item_id = str(top.get("item_id") or "(unidentified)")
    if item_id == "(unidentified)":
        return []
    views = int(top.get("zero_stock_views") or 0)
    users = int(top.get("affected_users") or 0)
    cart_adds = int(top.get("cart_adds") or 0)
    cart_users = int(top.get("cart_users") or 0)
    purchases = int(top.get("purchases") or 0)
    oos_pattern = str(top.get("oos_pattern") or "")
    if views < 3 or users < 1:
        return []

    backorder_allowed = oos_pattern == "backorder_allowed" or cart_adds > 0
    recovery_rate = INVENTORY_BACKORDER_RECOVERY_RATE if backorder_allowed else INVENTORY_RECOVERY_RATE

    monthly = None
    if aov is not None:
        monthly = round(users * aov * recovery_rate * 30, 2)

    if backorder_allowed:
        title = f"OOS messaging on {item_id}, but cart adds still occur"
        problem = (
            f"{users} users saw {views} zero-stock messages for {item_id}, "
            f"while {cart_adds} add-to-cart events still fired for the same SKU."
        )
        likely_cause = (
            "The storefront shows out-of-stock messaging but still allows backorder/cart adds — "
            "friction may appear later in checkout or fulfillment."
        )
        recommendation = (
            "Clarify backorder/availability on PDP and cart. Track checkout completion and "
            "post-order cancellations for this SKU; consider separate oos_add_to_cart tagging."
        )
        evidence = [
            f"{item_id} · {views} zero-stock views",
            f"{users} users saw OOS messaging",
            f"{cart_adds} add-to-cart events on the same SKU",
            f"{purchases} purchase line(s) in the period",
        ]
        confidence = 0.8 if users >= 3 else 0.68
    else:
        title = f"Demand is hitting unavailable {item_id}"
        problem = f"{users} buyers encountered {views} zero-stock views for {item_id}."
        likely_cause = "Shoppers are reaching products that show as unavailable on the PDP."
        recommendation = (
            "Confirm replenishment timing. If inventory cannot be restored, surface "
            "compatible in-stock alternatives on the PDP and in search."
        )
        evidence = [
            f"{item_id} · {views} zero-stock views",
            f"{users} users saw OOS messaging",
        ]
        confidence = 0.86 if users >= 3 else 0.72

    return [
        Opportunity(
            id=f"inventory-{item_id}",
            category="Inventory",
            title=title,
            problem=problem,
            likely_cause=likely_cause,
            evidence=evidence,
            recommendation=recommendation,
            confidence=confidence,
            date=date,
            estimated_monthly_revenue_usd=monthly,
            impact=impact_from_revenue(monthly),
            metrics={
                "item_id": item_id,
                "zero_stock_views": views,
                "affected_users": users,
                "cart_adds": cart_adds,
                "cart_users": cart_users,
                "purchases": purchases,
                "oos_pattern": "backorder_allowed" if backorder_allowed else "oos_messaging_only",
                "recovery_rate": recovery_rate,
            },
        )
    ]


def _search_opportunities(
    date: str,
    searches: list[dict[str, Any]],
    aov: float | None,
) -> list[Opportunity]:
    candidates = []
    for row in searches:
        if not isinstance(row, dict):
            continue
        term = row.get("search_term")
        search_count = int(row.get("searches") or 0)
        result_views = int(row.get("result_views") or 0)
        users = int(row.get("users") or 0)
        if not term or search_count < 5 or users < 1:
            continue
        # Unresolved intent: repeated searching with weak/no result-view signal.
        if result_views > 0 and result_views >= search_count:
            continue
        candidates.append(row)
    if not candidates:
        return []

    top = max(candidates, key=lambda row: (int(row.get("searches") or 0), int(row.get("users") or 0)))
    term = str(top["search_term"])
    search_count = int(top.get("searches") or 0)
    result_views = int(top.get("result_views") or 0)
    no_results = int(top.get("no_result_events") or 0)
    users = int(top.get("users") or 0)

    monthly = None
    if aov is not None:
        monthly = round(users * aov * SEARCH_RECOVERY_RATE * 30, 2)
    return [
        Opportunity(
            id=f"search-{_slug(term)}",
            category="Search",
            title=f"“{term}” shows unresolved intent",
            problem=(
                f"{users} buyer{'s' if users != 1 else ''} searched “{term}” "
                f"{search_count} times with weak result engagement."
            ),
            likely_cause=(
                "Search ranking, synonyms, or result-view tracking may be failing for this query."
            ),
            evidence=[
                f"{search_count} searches from {users} journey{'s' if users != 1 else ''}",
                f"{result_views} result-view and {no_results} no-result events observed",
            ],
            recommendation=(
                "Test this query in production, review matching products and synonyms, "
                "and verify result-view tracking carries the search term."
            ),
            confidence=0.78 if result_views == 0 else 0.70,
            date=date,
            estimated_monthly_revenue_usd=monthly,
            impact=impact_from_revenue(monthly),
            metrics={
                "search_term": term,
                "searches": search_count,
                "result_views": result_views,
                "no_result_events": no_results,
                "users": users,
                "recovery_rate": SEARCH_RECOVERY_RATE,
            },
        )
    ]


def _funnel_opportunities(
    date: str,
    funnel: dict[str, Any],
    aov: float | None,
    summary: dict[str, Any],
) -> list[Opportunity]:
    viewed = int(funnel.get("viewed_users") or 0)
    cart = int(funnel.get("cart_users") or 0)
    checkout = int(funnel.get("checkout_users") or 0)
    purchasers = int(funnel.get("purchasers") or 0)
    view_to_cart = float(funnel.get("view_to_cart_rate") or 0)
    if viewed < 50 or cart >= viewed:
        return []

    non_cart = viewed - cart
    cart_to_purchase = (purchasers / cart) if cart else 0.0
    daily_revenue = float(summary.get("revenue_usd") or 0)
    monthly = None
    if aov is not None and cart_to_purchase > 0:
        raw = non_cart * FUNNEL_RECOVERY_OF_NON_CART * cart_to_purchase * aov * 30
        if daily_revenue > 0:
            raw = min(raw, daily_revenue * FUNNEL_REVENUE_SHARE_CAP * 30)
        monthly = round(raw, 2)

    return [
        Opportunity(
            id="funnel-view-cart",
            category="Funnel",
            title="Product-view to cart is the largest funnel drop",
            problem=f"Only {cart} of {viewed} product-viewing users added an item to cart.",
            likely_cause=(
                "Friction after product discovery (availability, variants, pricing, or PDP clarity)."
            ),
            evidence=[
                f"{viewed} product viewers",
                f"{cart} cart users",
                f"{checkout} checkout users",
                f"{purchasers} purchasing users",
                f"{view_to_cart:.1%} view-to-cart rate",
            ],
            recommendation=(
                "Segment the drop by product, stock state, and search entry. "
                "Prioritize high-view products with low cart progression."
            ),
            confidence=0.74,
            date=date,
            estimated_monthly_revenue_usd=monthly,
            impact=impact_from_revenue(monthly),
            metrics={
                "viewed_users": viewed,
                "cart_users": cart,
                "checkout_users": checkout,
                "purchasers": purchasers,
                "view_to_cart_rate": view_to_cart,
                "assumed_recovery_of_non_cart": FUNNEL_RECOVERY_OF_NON_CART,
                "revenue_share_cap": FUNNEL_REVENUE_SHARE_CAP,
            },
        )
    ]


def _baseline_opportunities(
    date: str,
    series: list[dict[str, Any]],
    prior_dates: list[str],
    baseline_ready: bool,
) -> list[Opportunity]:
    if not baseline_ready or not prior_dates:
        return []
    by_date = {str(row.get("report_date")): row for row in series}
    current = by_date.get(date)
    priors = [by_date[d] for d in prior_dates if d in by_date]
    if not current or len(priors) < BASELINE_READY_PRIOR_DAYS:
        return []

    opportunities: list[Opportunity] = []
    current_rps = _as_float(current.get("revenue_per_session"))
    prior_rps = _mean([_as_float(row.get("revenue_per_session")) for row in priors])
    if current_rps is not None and prior_rps and prior_rps > 0:
        delta = (current_rps - prior_rps) / prior_rps
        if delta <= -REVENUE_ANOMALY_THRESHOLD:
            sessions = float(current.get("sessions") or 0)
            daily_gap = abs(delta) * prior_rps * sessions
            monthly = round(daily_gap * 30, 2)
            opportunities.append(
                Opportunity(
                    id="anomaly-revenue-per-session",
                    category="Anomaly",
                    title="Revenue per session fell versus baseline",
                    problem=(
                        f"Revenue/session is {abs(delta):.0%} below the prior "
                        f"{len(priors)}-day average."
                    ),
                    likely_cause="Conversion, mix, or traffic-quality shift versus recent baseline.",
                    evidence=[
                        f"Current revenue/session: {current_rps:.2f}",
                        f"Baseline revenue/session: {prior_rps:.2f}",
                        f"Prior days used: {len(priors)}",
                    ],
                    recommendation=(
                        "Investigate device, source, funnel, and top products for the decline window."
                    ),
                    confidence=0.88,
                    date=date,
                    estimated_monthly_revenue_usd=monthly,
                    impact=impact_from_revenue(monthly),
                    metrics={
                        "current_revenue_per_session": current_rps,
                        "baseline_revenue_per_session": prior_rps,
                        "delta": delta,
                        "prior_days": len(priors),
                    },
                )
            )

    current_vtc = _as_float(current.get("view_to_cart_rate"))
    prior_vtc = _mean([_as_float(row.get("view_to_cart_rate")) for row in priors])
    if current_vtc is not None and prior_vtc and prior_vtc > 0:
        delta = (current_vtc - prior_vtc) / prior_vtc
        if delta <= -FUNNEL_ANOMALY_THRESHOLD:
            opportunities.append(
                Opportunity(
                    id="anomaly-view-to-cart",
                    category="Anomaly",
                    title="View-to-cart rate deteriorated versus baseline",
                    problem=(
                        f"View-to-cart is {abs(delta):.0%} below the prior "
                        f"{len(priors)}-day average."
                    ),
                    likely_cause="PDP, availability, or merchandising friction increased.",
                    evidence=[
                        f"Current view-to-cart: {current_vtc:.1%}",
                        f"Baseline view-to-cart: {prior_vtc:.1%}",
                        f"Prior days used: {len(priors)}",
                    ],
                    recommendation=(
                        "Compare zero-stock views and top PDP performers against the baseline window."
                    ),
                    confidence=0.84,
                    date=date,
                    estimated_monthly_revenue_usd=None,
                    impact="Medium",
                    metrics={
                        "current_view_to_cart_rate": current_vtc,
                        "baseline_view_to_cart_rate": prior_vtc,
                        "delta": delta,
                        "prior_days": len(priors),
                    },
                )
            )
    return opportunities


def _validate_date(date: str) -> None:
    try:
        datetime.strptime(date, "%Y%m%d")
    except ValueError as exc:
        raise ValueError("Dates must use YYYYMMDD format") from exc


def _slug(value: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "-" for ch in value.strip())
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-")[:48] or "term"


def _as_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _mean(values: list[float | None]) -> float | None:
    present = [value for value in values if value is not None]
    if not present:
        return None
    return sum(present) / len(present)


def lookback_start(date: str, days: int) -> str:
    parsed = datetime.strptime(date, "%Y%m%d").date()
    return (parsed - timedelta(days=days)).strftime("%Y%m%d")
